[package]
name = "rectree"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/voxell-tech/rectree"
description = "Representing user interfaces using a rectangle tree."
keywords = ["rectangle", "layout", "user-interface", "hierarchy", "box"]
categories = ["gui", "data-structures", "no-std"]
readme = "README.md"

[dependencies]
bitflags = { version = "2", default-features = false }

[dev-dependencies]
hashbrown = { version = "0.16.1", default-features = false, features = ["default-hasher", "inline-more"] }
kurbo = { version = "0.13.1", default-features = false, features = ["std"] }
vello = "0.7"
winit = "0.30.12"
pollster = "0.4.0"
